services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: algochef
      POSTGRES_PASSWORD: algochef
      POSTGRES_DB: algochef
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
